apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: stebanrodriguez/app-auth-api:0.1.1
        ports:
        - containerPort: 8000
        env:
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        - name: JWT_SECRET
          value: "PRFT"
        - name: USERS_API_ADDRESS
          value: "http://users-api:8083"
        - name: AUTH_API_PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
