apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-channel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-channel
  template:
    metadata:
      labels:
        app: log-channel
    spec:
      containers:
      - name: log-channel
        image: stebanrodriguez/app-log-message:0.1.0
        ports:
        - containerPort: 6060
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log-channel"
---
apiVersion: v1
kind: Service
metadata:
  name: log-channel
spec:
  selector:
    app: log-channel
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060