apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
      - name: todos-api
        image: stebanrodriguez/app-todos-api:0.1.0
        ports:
        - containerPort: 8082
        env:
        - name: ZIPKIN_URL
          value: "http://zipkin:9411/api/v2/spans"
        - name: JWT_SECRET
          value: "PRFT"
        - name: TODO_API_PORT
          value: "8082"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log-channel"

---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
spec:
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
