apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: stebanrodriguez/app-users-api:0.1.0
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411"
        - name: JWT_SECRET
          value: "PRFT"
        - name: SERVER_PORT
          value: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
